// Generated by https://quicktype.io

export interface TrendingCurrencyResponse {
  RAW: {[key: string]: Raw};
  DISPLAY: {[key: string]: Display};
}

export interface Display {
  USD: {[key: string]: string};
}

export interface Raw {
  USD: Usd;
}

export interface Usd {
  TYPE: string;
  MARKET: Market;
  FROMSYMBOL: string;
  TOSYMBOL: Tosymbol;
  FLAGS: string;
  PRICE: number;
  LASTUPDATE: number;
  MEDIAN: number;
  LASTVOLUME: number;
  LASTVOLUMETO: number;
  LASTTRADEID: string;
  VOLUMEDAY: number;
  VOLUMEDAYTO: number;
  VOLUME24HOUR: number;
  VOLUME24HOURTO: number;
  OPENDAY: number;
  HIGHDAY: number;
  LOWDAY: number;
  OPEN24HOUR: number;
  HIGH24HOUR: number;
  LOW24HOUR: number;
  LASTMARKET: string;
  VOLUMEHOUR: number;
  VOLUMEHOURTO: number;
  OPENHOUR: number;
  HIGHHOUR: number;
  LOWHOUR: number;
  TOPTIERVOLUME24HOUR: number;
  TOPTIERVOLUME24HOURTO: number;
  CHANGE24HOUR: number;
  CHANGEPCT24HOUR: number;
  CHANGEDAY: number;
  CHANGEPCTDAY: number;
  CHANGEHOUR: number;
  CHANGEPCTHOUR: number;
  CONVERSIONTYPE: Conversiontype;
  CONVERSIONSYMBOL: Conversionsymbol;
  SUPPLY: number;
  MKTCAP: number;
  MKTCAPPENALTY: number;
  TOTALVOLUME24H: number;
  TOTALVOLUME24HTO: number;
  TOTALTOPTIERVOLUME24H: number;
  TOTALTOPTIERVOLUME24HTO: number;
  IMAGEURL: string;
}

export enum Conversionsymbol {
  Btc = 'BTC',
  Empty = '',
  Usdt = 'USDT',
}

export enum Conversiontype {
  Direct = 'direct',
  Multiply = 'multiply',
}

export enum Market {
  Cccagg = 'CCCAGG',
}

export enum Tosymbol {
  Usd = 'USD',
}
